name: Build and Publish Agent KB Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: stackdrift
    uses: stackdrift-images/ci-templates/.forgejo/workflows/docker-build.yml@main
    with:
      image_name: codeberg.org/stackdrift/agent-working-knowledge
      upstream_image_search: squidfunk/mkdocs-material
      upstream_name_short: mkdocs
    secrets:
      registry_password: ${{ secrets.REGISTRY_DEPLOY_KEY }}
